apiVersion :  apps/v1
kind : Deployment
metadata : 
  name : mydeployment
  labels :
    app : nginx
spec:
  replicas : 2
  minReadySeconds : 10
  strategy :
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector :
    matchLabels :
      app : nginx 
  template :
      metadata :
        labels:
          app : nginx
      spec : 
        hostNetwork : true
        containers:
        - name : depconainer
          image : httpd
        # image: nginx
          ports:
          - containerPort : 8080